name: Build Squirrel

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download 461 targeting pack
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        id: downloadfile # Remember to give an ID if you need the output filename
        with:
          url: "https://download.microsoft.com/download/F/1/D/F1DEB8DB-D277-4EF9-9F48-3A65D4D8F965/NDP461-DevPack-KB3105179-ENU.exe"
          target: public/

      - name: Install targeting pack
        shell: cmd
        working-directory: public
        run: NDP461-DevPack-KB3105179-ENU.exe /q

      - name: Build Squirrel
        shell: cmd
        run: ./src/build_official.cmd

      - name: Test Squirrel
        shell: cmd
        run: ./test/test_official.cmd
